export const Trabalhos = [
    {
        id: 1,
        imagens: ['./img/trabalhos/Thaina-Erick-prewedding/1.jpeg',
                    './img/trabalhos/Thaina-Erick-prewedding/2.jpeg',
                    './img/trabalhos/Thaina-Erick-prewedding/3.jpeg',
                    './img/trabalhos/Thaina-Erick-prewedding/4.jpeg',
                    './img/trabalhos/Thaina-Erick-prewedding/5.jpeg',
                    './img/trabalhos/Thaina-Erick-prewedding/6.jpeg',
                    './img/trabalhos/Thaina-Erick-prewedding/7.jpeg',
                    './img/trabalhos/Thaina-Erick-prewedding/8.jpeg',
                    './img/trabalhos/Thaina-Erick-prewedding/9.jpeg',
                    './img/trabalhos/Thaina-Erick-prewedding/10.jpeg',
                    './img/trabalhos/Thaina-Erick-prewedding/11.jpeg',],
        categoria: 'Pré Wedding',
        nome: 'Erick & Thainá'
    },
    {
        id: 2,
        imagens: ['./img/trabalhos/Danielle-Wellerson-casamento/1.jpg',
            './img/trabalhos/Danielle-Wellerson-casamento/2.jpg',
            './img/trabalhos/Danielle-Wellerson-casamento/3.jpg',
            './img/trabalhos/Danielle-Wellerson-casamento/4.jpg',
            './img/trabalhos/Danielle-Wellerson-casamento/5.jpg',
            './img/trabalhos/Danielle-Wellerson-casamento/6.jpg',
            './img/trabalhos/Danielle-Wellerson-casamento/7.jpg',
            './img/trabalhos/Danielle-Wellerson-casamento/8.jpg',
            './img/trabalhos/Danielle-Wellerson-casamento/9.jpg',
            './img/trabalhos/Danielle-Wellerson-casamento/10.jpg',
            './img/trabalhos/Danielle-Wellerson-casamento/11.jpg',
        ],
        categoria: 'Casamento',
        nome: 'Wellerson & Danielle'
    },
    {
        id: 3,
        imagens: ['./img/trabalhos/Fernanda-Henrique-externa/1.jpg',
            './img/trabalhos/Fernanda-Henrique-externa/2.jpg',
            './img/trabalhos/Fernanda-Henrique-externa/3.jpg',
            './img/trabalhos/Fernanda-Henrique-externa/4.jpg',
            './img/trabalhos/Fernanda-Henrique-externa/5.jpg',
            './img/trabalhos/Fernanda-Henrique-externa/6.jpg',
            './img/trabalhos/Fernanda-Henrique-externa/7.jpg',
            './img/trabalhos/Fernanda-Henrique-externa/8.jpg',
            './img/trabalhos/Fernanda-Henrique-externa/9.jpg',
            './img/trabalhos/Fernanda-Henrique-externa/10.jpg',
            './img/trabalhos/Fernanda-Henrique-externa/11,jpg',
            './img/trabalhos/Fernanda-Henrique-externa/12.jpg',
            './img/trabalhos/Fernanda-Henrique-externa/13.jpg',
        ],
        categoria: 'Externo',
        nome: 'Henrique & Fernanda'
    },
    {
        id: 4,
        imagens: ['./img/trabalhos/Alessandra-lifystyle/1.jpg',
                './img/trabalhos/Alessandra-lifystyle/2.jpg',
                './img/trabalhos/Alessandra-lifystyle/3.jpg',
                './img/trabalhos/Alessandra-lifystyle/4.jpg',
                './img/trabalhos/Alessandra-lifystyle/5.jpg',
                './img/trabalhos/Alessandra-lifystyle/6.jpg',
                './img/trabalhos/Alessandra-lifystyle/7.jpg',
                './img/trabalhos/Alessandra-lifystyle/8.jpg',
                './img/trabalhos/Alessandra-lifystyle/9.jpg',
                './img/trabalhos/Alessandra-lifystyle/10.jpg',
        ],
        categoria: 'LifeStyle',
        nome: 'Alessandra'
    },
    {
        id: 5,
        imagens: ['./img/trabalhos/Aghata-jordan-casamento/1.jpg',
                './img/trabalhos/Aghata-jordan-casamento/2.jpg',
                './img/trabalhos/Aghata-jordan-casamento/3.jpg',
                './img/trabalhos/Aghata-jordan-casamento/4.jpg',
                './img/trabalhos/Aghata-jordan-casamento/5.jpg',
                './img/trabalhos/Aghata-jordan-casamento/6.jpg',
                './img/trabalhos/Aghata-jordan-casamento/7.jpg',
                './img/trabalhos/Aghata-jordan-casamento/8.jpg',
                './img/trabalhos/Aghata-jordan-casamento/9.jpg',
                './img/trabalhos/Aghata-jordan-casamento/10.jpg',
                './img/trabalhos/Aghata-jordan-casamento/11.jpg',
        ],
        categoria: 'Casamento',
        nome: 'Jordan & Agatha'
    },
    {
        id: 6,
        imagens: [
            './img/trabalhos/Hevellyn-Hiago-prewedding/1.jpg',
            './img/trabalhos/Hevellyn-Hiago-prewedding/2.jpg',
            './img/trabalhos/Hevellyn-Hiago-prewedding/3.jpg',
            './img/trabalhos/Hevellyn-Hiago-prewedding/4.jpg',
            './img/trabalhos/Hevellyn-Hiago-prewedding/5.jpg',
            './img/trabalhos/Hevellyn-Hiago-prewedding/6.jpg',
            './img/trabalhos/Hevellyn-Hiago-prewedding/7.jpg',
            './img/trabalhos/Hevellyn-Hiago-prewedding/8.jpg',
            './img/trabalhos/Hevellyn-Hiago-prewedding/9.jpg',
            './img/trabalhos/Hevellyn-Hiago-prewedding/10.jpg',
            './img/trabalhos/Hevellyn-Hiago-prewedding/11.jpg',
            './img/trabalhos/Hevellyn-Hiago-prewedding/12.jpg',

        ],
        categoria: 'Pré Wedding',
        nome: 'Hiago & Hevellyn'
    },
    {
        id: 7,
        imagens: [
            './img/trabalhos/Débora-Elkis-casamento/1.jpg',
            './img/trabalhos/Débora-Elkis-casamento/2.jpg',
            './img/trabalhos/Débora-Elkis-casamento/3.jpg',
            './img/trabalhos/Débora-Elkis-casamento/4.jpg',
            './img/trabalhos/Débora-Elkis-casamento/5.jpg',
            './img/trabalhos/Débora-Elkis-casamento/6.jpg',
            './img/trabalhos/Débora-Elkis-casamento/7.jpg',
            './img/trabalhos/Débora-Elkis-casamento/8.jpg',
            './img/trabalhos/Débora-Elkis-casamento/9.jpg',
            './img/trabalhos/Débora-Elkis-casamento/10.jpg',
            './img/trabalhos/Débora-Elkis-casamento/11.jpg',
            './img/trabalhos/Débora-Elkis-casamento/12.jpg',
            './img/trabalhos/Débora-Elkis-casamento/13.jpg',
            './img/trabalhos/Débora-Elkis-casamento/14.jpg',
            './img/trabalhos/Débora-Elkis-casamento/15.jpg',
        ],
        categoria: 'Casamento',
        nome: 'Elkis & Débora'
    },
    {
        id:8,
        imagens: ['./img/trabalhos/Marlon-Thayane-prewedding/1.jpg',
                './img/trabalhos/Marlon-Thayane-prewedding/2.jpg',
                './img/trabalhos/Marlon-Thayane-prewedding/3.jpg',
                './img/trabalhos/Marlon-Thayane-prewedding/4.jpg',
                './img/trabalhos/Marlon-Thayane-prewedding/5.jpg',
                './img/trabalhos/Marlon-Thayane-prewedding/6.jpg',
                './img/trabalhos/Marlon-Thayane-prewedding/7.jpg',
                './img/trabalhos/Marlon-Thayane-prewedding/8.jpg',
                './img/trabalhos/Marlon-Thayane-prewedding/9.jpg',
                './img/trabalhos/Marlon-Thayane-prewedding/10.jpg',
                './img/trabalhos/Marlon-Thayane-prewedding/11.jpg',
                './img/trabalhos/Marlon-Thayane-prewedding/12.jpg',
        ],
        categoria: 'Pré Wedding',
        nome: 'Marlon & Thayane'
    },

]